items/urls.py
from django.conf.urls import url
from .views import *
from rest_framework.routers import DefaultRouter
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='add'),
    url(r'^ticket/(?P<slug>[\w-]+)/$', views.get_ticket_by_slug, name='get_ticket_by_slug'),
    url(r'^(?P<slug>[\w-]+)/$', views.get_ticket_by_slug_to_user, name='get_ticket_by_slug_to_user'),
    url(r'^ticket/(?P<ticket>[\w-]+)/product/(?P<product>[\w-]+)$', views.add_product_to_ticket, name='add_product_to_ticket'),
    url(r'^ticket/(?P<ticket>[\w-]+)/product/(?P<product>[\w-]+)/delete/$', views.remove_product_from_ticket, name='remove_product_from_ticket'),
    url(r'^ticket/(?P<ticket>[\w-]+)/product/(?P<product>[\w-]+)/pay/$', views.pay_product_from_ticket, name='pay_product_from_ticket'),
    url(r'^ticket/(?P<slug>[\w-]+)/close/$', views.close_ticket_by_slug, name='close_ticket_by_slug'),
    url(r'^ticket/(?P<ticket>[\w-]+)/product/(?P<product>[\w-]+)/price/(?P<price>\d+\.\d{2})/$', views.add_product_without_price_to_ticket, name='add_product__without_price_to_ticket'),
    url(r'^ticket/(?P<ticket>[\w-]+)/discount/(?P<price>\d+\.\d{2})/$', views.give_discount_to_ticket, name='give_discount_to_ticket'),
    url(r'^invalid/ticket/$', views.show_invalid_page, name='show_invalid_page'),
    url(r'^api/products/(?P<name>.+)/$', ProductSearch.as_view()),
]

product_router = DefaultRouter()
product_router.register(r'products', ProductViewSet)

kanovaitems/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from items.urls import product_router

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('items.urls')),
    url(r'^api/', include(product_router.urls)),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/models.py
from django.db import models
from django.utils.text import slugify
from django.conf import settings


class Color(models.Model):
    name = models.CharField(max_length=250, blank=False, default='')
    hex = models.CharField(max_length=6, blank=False, default='')

    class Meta:
        verbose_name = "Cor"
        verbose_name_plural = "Cores"

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=250, blank=False, default='')
    description = models.CharField(max_length=250, blank=True)
    color = models.ForeignKey(Color, null=True, blank=True)

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=250, blank=False, default='')
    description = models.CharField(max_length=250, blank=True)

    class Meta:
        verbose_name = "Marca"
        verbose_name_plural = "Marca"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=128, null=False, blank=False)
    slug = models.SlugField(null=False, blank=True)
    description = models.CharField(max_length=128, null=True, blank=True)
    active = models.BooleanField(default=True)
    price = models.DecimalField(decimal_places=2, max_digits=6, null=True, blank=True)
    stock = models.IntegerField(null=True, blank=True)
    barcode = models.IntegerField(null=True, blank=True)
    category = models.ForeignKey(Category, related_name='products', null=True, blank=True)
    brand = models.ForeignKey(Brand, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Produto"
        verbose_name_plural = "Produtos"

    def __str__(self):
        return self.name


class Ticket(models.Model):
    name = models.CharField(max_length=250, blank=False, null=False)
    slug = models.SlugField(unique=True, blank=True, null=False)
    number = models.BigIntegerField(null=True, blank=True, unique=False)
    products = models.ManyToManyField(Product, through='Quantity', blank=True)
    finalPrice = models.DecimalField(decimal_places=2, max_digits=6, null=True, blank=True)
    partialPaid = models.DecimalField(decimal_places=2, max_digits=6, null=True, blank=True)
    createdBy = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)
    createdAt = models.DateTimeField(auto_now=True, null=True)
    isFinished = models.BooleanField(default=False)
    documentNumber = models.IntegerField(null=True, blank=True)

    class Meta:
        verbose_name = "Comanda"
        verbose_name_plural = "Comandas"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)  # set the slug explicitly
        super(Ticket, self).save(*args, **kwargs)  # call Django's save()

    def __str__(self):
        if self.name:
            return str(self.name)
        return str(self.number)


class Quantity(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    class Meta:
        verbose_name = "Quantidade"
        verbose_name_plural = "Quantidades"

    def __str__(self):
        return str(self.quantity)

frontend/templates/add.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div>
  <div class='row'>
    <div class='col-sm-12 center-text'>
      <h3>Adicionar comanda</h3>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <div class='panel panel-default'>
        <div class='panel-body'>
          <form action="/add/" method="post">
            {% csrf_token %}
            <div>
              <label for="ticket_name" class='control-label'>Nome</label> {{ form.ticket_name }}
            </div>
            <div style="margin-top: 10px">
              <label for="ticket_name" class='control-label'>Mesa</label> {{ form.ticket_number }}
            </div>
            <input type='submit' class='btn btn-primary' value="Criar comanda" style="margin-top: 10px" />
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12 center-text'>
      <h3>Comandas ativas</h3>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <ul class="list-group">
        {% for ticket in tickets %}
        <li key={card.slug} class="list-group-item">
          <div class='row'>
            <div class='col-sm-9'>
              <a href="/ticket/{{ ticket.slug }}">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <span class="card-name">{% if ticket.number %} 
								{{ ticket.name}} - {{ ticket.number }}
								{% else %}
								{{ ticket.name }}
								{% endif %} </span>
              </a>
            </div>
            <div class='col-sm-3 right-text'>
              <span class="card-value">
								{% if ticket.finalPrice %} 
								R${{ticket.finalPrice}}
								 {% else %} 
								N/D {% endif %}</span>
              <a class="glyphicon glyphicon-trash card-delete" aria-hidden="true"></a>
            </div>
          </div>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock content %}

frontend/templates/base.html
<!DOCTYPE html> {% load static %}
<html lang="pt-BR">

<head>
  <title>Komanda Kanova</title>
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <!-- Bootstrap -->

  <link rel="stylesheet" media="all" href="{% static 'vendor/bootstrap/dist/css/bootstrap.min.css' %}">

  <link href='https://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>

  <link rel="stylesheet" media="all" href="{% static 'vendor/fontawesome/css/font-awesome.min.css' %}">
  <link rel="stylesheet" media="all" href="{% static 'css/style.css' %}">
</head>

<body>
  <div class="container">
    <div class='row'>
      <div class='col-sm-12 center-text'>
        <a href='/'><img src="{% static 'img/LogoKomanda.png' %}" alt="Komanda by Kanova" class="logo" /></a>
      </div>
    </div>
    <!-- #################### -->
    <!-- DJANGO BLOCK CONTENT -->
    <!-- #################### -->
    <div class="content-top-margin">
      {% block content %} {% endblock %}
    </div>
  </div>
  <!-- ######################## -->
  <!-- END DJANGO BLOCK CONTENT -->
  <!-- ######################## -->


  <script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/jquery-ui/jquery-ui.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'vendor/jquery-mask/jquery.mask.min.js' %}"></script>

</body>

</html>

frontend/templates/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div>
	<div class='row'>
		<div class='col-sm-12 center-text'>
			<h3>Comandas ativas</h3>
		</div>
	</div>
	{% if tickets.all %}
	<div class='row'>
		<div class='col-sm-12'>
			<ul class="list-group">
				{% for ticket in tickets %}
				<li key={card.number} class="list-group-item">
					<div class='row'>
						<div class='col-sm-9'>
							<a href="/ticket/{{ticket.slug}}">
							<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
							<span class="card-name">{% if ticket.number %} 
								{{ ticket.name}} - {{ ticket.number}}
								{% else %}
								{{ ticket.name }}
								{% endif %} </span>
								</a>
						</div>
						<div class='col-sm-3 right-text'>
							<span class="card-value">
								{% if ticket.finalPrice %} 
								R${{ticket.finalPrice}}
								 {% else %} 
								N/D {% endif %}</span>
						</div>
					</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	{% else %}
	<div class='row'>
		<div class='col-sm-12 center-text no-results' style='margin-bottom: 20px'>
			Ainda não há comandas ativas
		</div>
	</div>
	{% endif %}
	<div class='row'>
		<div class='col-sm-12 center-text'>
			<a href="/add">
				<button type="button" class="btn btn-success center-button">Adicionar comanda</button>
			</a>
		</div>
	</div>
</div>
{% endblock content %}

frontend/templates/invalid.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div>
	<div class='row'>
		<div class='col-sm-12 center-text'>
			<h3>Alguma coisa não deu certo!</h3>
		</div>
	</div>
	<div class='row'>
		<div class='col-sm-12 center-text no-results'>
			Esta comanda já está aberta!
		</div>
	</div>
	<div class='row'>
		<div class='col-sm-12 center-text'>
			<a href="/add">
				<button type="button" class="btn btn-success center-button">Adicionar comanda</button>
			</a>
		</div>
	</div>
</div>
{% endblock content %}

frontend/templates/ticket.html
{% extends 'base.html' %} {% load static %} {% block content %}

<script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>

<script>
  let timeout
  let price
  let link
  let product
  let newPrice

  function searchProducts(product) {
    $.ajax({
      'url': '/api/products/' + product + '/',
      'type': 'GET',
      'dataType': 'json',
      'success': function (data) {
        $("#product_list").hide()
        for (i in data) {
          if (!data[i]['price'] || data[i]['price'] == 0) {
            price = 'Sem preço'
            link = ''
          } else {
            price = 'R$' + data[i]['price']
            link = 'href=/ticket/{{ticket.slug}}/product/' + data[i]['id']
          }
          $('ul#product_list').append(
            "<li class='list-group-item'>" +
            "<div class='row'>" +
            "<div class='col-sm-9'>" +
            "<span class='card-name'>" +
            data[i]['name'] +
            "</span>" +
            "</div>" +
            "<div class='col-sm-3 right-text'>" +
            "<span class='card-value'>" +
            price +
            "</span>" +
            "<a " + link + " class='glyphicon glyphicon-plus card-add noPrice" + data[i]['id'] + "' value='Adicionar' aria-hidden='true'/>" +
            "</div>" +
            "</div>" +
            "</li>")

          if (!data[i]['price'] || data[i]['price'] == 0) {
            product = data[i]['id']
            $('.noPrice' + data[i]['id']).on('click', function () {
              $('#modal2').modal('show')

              $('.no-price').append(
                "<a id='" + product + "'href='/ticket/{{ticket.slug}}/product/" + data[i]['id'] + "/price/" + newPrice + "' >" +
                "<button type='button' class='btn btn-success'>Confirmar</button></a>"
              )
            })
          }
        }
        $("#product_list").show()
      }
    })
  }

  function changePrice() {
    newPrice = $('#newPrice').val()
    console.log(newPrice)
    let element = $('#' + product)
    $(element).attr('href', '/ticket/{{ticket.slug}}/product/' + product + '/price/' + newPrice)
    console.log($(element).attr('href'))
  }

  function changeDiscountPrice() {
    let discountValue = $('.discountValue').val()
    console.log($('.discountValue').val())
    console.log(discountValue)
    let element = $('.discount')
    $(element).attr('href', '/ticket/{{ticket.slug}}/discount/' + discountValue)
    console.log($(element).attr('href'))
  }

  function filter(element) {
    clearTimeout(timeout)
    $("#product_list").children("li").remove()
    let value = $(element).val()

    value = value.toUpperCase()

    if (value == '') {
      $("#product_list").hide()
    } else {
      timeout = setTimeout(function () { searchProducts(value) }, 500)
    }
  }

</script>

<div>
  <div class='row'>
    <div class='col-sm-12 center-text'>
      <h3>Comanda: {{ticket.name}} {% if ticket.number %} - {{ ticket.number }} {% endif %}
      </h3>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <div class='panel panel-default'>
        <div class='panel-body'>
          <form action="/add/" method="post">
            <div>
              <label for="ticket_name" class='control-label'>Pesquisar produto</label>
              <input type="text" class="form-control" id='search' placeholder="Digite o nome ou marca do produto" onkeyup="filter(this)"
              />
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <ul class="list-group" id='product_list'>

      </ul>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12 center-text'>
      <h3>Produtos</h3>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <ul class="list-group">
        {% if ticket.products.all %} {% for quantity in ticket.quantity_set.all %}
        <li class="list-group-item">
          <div class="row visible-xs">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="col-md-9 col-sm-9 col-xs-9">
                <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>
                <span class="card-name">
								{{ quantity.product.name }} ({{ quantity }})
							 </span>
              </div>
              <div class="col-md-3 col-sm-3 col-xs-3" style="text-align: right;">
                <span class="card-value">
								{% if quantity.product.price %} 
								R${{ quantity.product.price }}
								 {% else %} 
								N/D {% endif %}</span>
              </div>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12" style="padding-top:15px">
              <div class="col-md-4 col-sm-4 col-xs-4" style="text-align: center;">
                <a class="glyphicon glyphicon-plus card-sucess" href="/ticket/{{ ticket.slug }}/product/{{ quantity.product.id }}" aria-hidden="true"></a>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-4" style="text-align: center;">
                {% if quantity.product.price %}
                <a class="glyphicon glyphicon-usd card-sucess" href="/ticket/{{ ticket.slug }}/product/{{ quantity.product.id }}/pay" aria-hidden="true"></a>                {% endif %}
              </div>
              <div class="col-md-4 col-sm-4 col-xs-4" style="text-align: center;">
                <a class="glyphicon glyphicon-trash card-delete" href="/ticket/{{ ticket.slug }}/product/{{ quantity.product.id }}/delete"
                  aria-hidden="true"></a>
              </div>
            </div>
          </div>
          <div class='row hidden-xs'>
            <div class='col-sm-9'>
              <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>
              <span class="card-name">
								{{ quantity.product.name }} ({{ quantity }})
							 </span>
            </div>
            <div class='col-sm-3 right-text'>
              <span class="card-value">
                <a class="glyphicon glyphicon-plus card-sucess" href="/ticket/{{ ticket.slug }}/product/{{ quantity.product.id }}" aria-hidden="true"></a>  
								{% if quantity.product.price %} 
								R${{ quantity.product.price }}
								 {% else %} 
								N/D {% endif %}</span> {% if quantity.product.price %}
              <a class="glyphicon glyphicon-usd card-sucess" href="/ticket/{{ ticket.slug }}/product/{{ quantity.product.id }}/pay" aria-hidden="true"></a>              {% endif %}
              <a class="glyphicon glyphicon-trash card-delete" href="/ticket/{{ ticket.slug }}/product/{{ quantity.product.id }}/delete"
                aria-hidden="true"></a>
            </div>
          </div>
        </li>
        {% endfor %} {% else %}
        <div class='row'>
          <div class='col-sm-12 center-text no-results'>
            Ainda não há produtos nesta comanda
          </div>
        </div>
        {% endif %}
      </ul>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-6 no-results'>
      <button id="closeTicket" type="button" class="btn btn-warning center-button">Finalizar comanda</button>
      <button id="discountValue" type="button" class="btn btn-success center-button">Descontar valor</button>
    </div>
    <div class='col-sm-6 right-text no-results'>
      {% if ticket.finalPrice %}
      <div class='col-sm-12 right-text no-results'>
        Total: R${{ ticket.finalPrice }}
      </div>
      {% endif %} {% if ticket.partialPaid %}
      <div class='col-sm-12 right-text no-results'>
        Valor pago: R${{ ticket.partialPaid }}
      </div>
      {% endif %}
    </div>
  </div>
</div>
<div class="modal fade" id="modal" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Atenção</h4>
      </div>
      <div class="modal-body">
        Ainda há R${{ leftToPay }} restantes nesta comanda. Tem certeza que deseja finalizá-la?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <a href="/ticket/{{ticket.slug}}/close/"><button type="button" class="btn btn-success">Sim</button></a>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="modal2" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Atenção</h4>
      </div>
      <div class="modal-body">
        Este produto não tem preço. Adicione um preço:

        <div class="input-group">
          <span class="input-group-addon">R$</span>
          <input type="text" id="newPrice" class="form-control format-mask" onkeyup="changePrice()" />
        </div>
      </div>
      <div class="modal-footer no-price">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="modal3" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Atenção</h4>
      </div>
      <div class="modal-body">
        Informe o valor a ser descontado desta comanda:

        <div class="input-group">
          <span class="input-group-addon">R$</span>
          <input type="text" class="form-control discountValue format-mask" onkeyup="changeDiscountPrice()" />
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <a href="#" class="discount"><button type='button' class='btn btn-success'>Confirmar</button></a>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<script>
  $('#closeTicket').on('click', function () {
    $('#modal').modal('show')
  })

  $('#discountValue').on('click', function () {
    $('#modal3').modal('show')
  })

  $(document).ready(function () {
    $('.format-mask').mask("#,##0.00", { reverse: true });
  });

</script>

{% endblock content %}

frontend/templates/user.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div>
  <div class='row'>
    <div class='col-sm-12 center-text'>
      <h3>Comanda número: {{ticket.name}} {% if ticket.number %} - {{ ticket.number }} {% endif %}
      </h3>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12 center-text'>
      <h3>Produtos</h3>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <ul class="list-group">
        {% if ticket.products.all %} {% for quantity in ticket.quantity_set.all %}
        <li class="list-group-item">
          <div class='row'>
            <div class='col-sm-9'>
              <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>
              <span class="card-name">
								{{ quantity.product.name }} ({{ quantity }})
							 </span>
            </div>
            <div class='col-sm-3 right-text'>
              <span class="card-value">
								{% if quantity.product.price %} 
								R${{ quantity.product.price }}
								 {% else %} 
								N/D {% endif %}</span>
              <a class="glyphicon glyphicon-trash card-delete" href="/ticket/{{ ticket.slug }}/product/{{ quantity.product.id }}/delete" aria-hidden="true"></a>
              <a class="glyphicon glyphicon-usd card-sucess" href="/ticket/{{ ticket.slug }}/product/{{ quantity.product.id }}/pay" aria-hidden="true"></a>
            </div>
          </div>
        </li>
        {% endfor %} {% else %}
        <div class='row'>
          <div class='col-sm-12 center-text no-results'>
            Ainda não há produtos nesta comanda
          </div>
        </div>
        {% endif %}
      </ul>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-6 right-text no-results'>
      {% if ticket.finalPrice %}
      <div class='col-sm-12 right-text no-results'>
        Total: R${{ ticket.finalPrice }}
      </div>
      {% endif %} {% if ticket.partialPaid %}
      <div class='col-sm-12 right-text no-results'>
        Valor pago: R${{ ticket.partialPaid }}
      </div>
      {% endif %}
    </div>
  </div>
</div>


{% endblock content %}